language: python
python:
- '3.6'
sudo: required
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
  - secure: S1XMzg5JztSkbRgSn1xfm3E9hV/RpwKLKfL3xFGXleI+RIHv+/6LQIM6XnK6NCmIxdlR1CGsIPC8A1J4LOA/+XcoBWyrmBmKNZbb7zTODYzC3SX9PayyZ+5O8oB+zHvvoTuzkhzyovHp3E5Xt3RlJSniqX7DAo9NurWtYlGiRov2HXvX+xPXW8k+rkTtOksN9bc6Lwzbc5trwRow3Q72x23VpD0k9N1gGlvRdcnlBmAlQf+1oghXcXlOmao58m19jXxc4jAzkKH7yWl0G2IfFoynb+WrJtbWIQp+2+9Nr0Q4LBaPIyWAZRKXFOZ5A4lyNDjgFd6mR67+wqtPCyIUIg9EzvRYuJqUUHuC3s36+s/7sk1B6QZMq58v9Ivu81kwe9WpNQMoYUxdE54QDllNGWK4coHmc/wO+teabfprufzy0oRo7mVMjasR8GIf9uSmP1Qbjn41wFwiI/cAkHMhNpwUlbdbsy5Ms7q+k9jMVl4Rl+ttCUWNkshzcmNF/FC94OvtTRN6Ur2yE1JzAzzwp2UsIOXdBoqJo4GCEpVJXUv2NBxAAPUABI32ehjV5LUnxwQLPhqurbjRJSNQD9DTX/p8ui86cwdMbIP5c+pBOeL0LSzaqEH/kM2y8ND8fUg72MPDvrAR4qvxR3wmB+NduQ3AtqHD0XiL5lAK+Bhu//E=
